#!/usr/bin/env node
/* Cross-check: JS (tweetnacl + did.js) vs reference vectors from python cryptography.
 * Run: node test/crosscheck.js  (node_modules not needed; nacl is vendored)
 */
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const vm = require('vm');

// --- load sha256.js into a sandbox ---
const sandbox = { self: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, 'js/sha256.js'), 'utf8'), sandbox);
global.SHA256 = sandbox.self.SHA256;

// --- load tweetnacl ---
global.nacl = require(path.join(root, 'js/vendor/tweetnacl.min.js'));

// --- load did.js (needs TextEncoder, btoa, fetch stubs) ---
const { TextEncoder } = require('util');
global.TextEncoder = TextEncoder;
global.btoa = (s) => Buffer.from(s, 'binary').toString('base64');
global.fetch = async () => { throw new Error('no fetch in test'); };
const didSrc = fs.readFileSync(path.join(root, 'js/did.js'), 'utf8');
const didMod = { exports: {} };
new Function('module', 'exports', 'require', 'nacl', 'SHA256', 'self', didSrc + '\n;module.exports = DID;')(
  didMod, didMod.exports, require, nacl, SHA256, globalThis);
const DID = didMod.exports;

// --- vectors generated by python cryptography (see crosscheck.py) ---
const VECTORS = [
  { seed: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f' },
  { seed: '476d7b5ae33da96a4b99e824e06f6c311247ce0b94eee32097f24a8196658e0d' },
];
// python crosscheck.py prints these; we paste here after first run
const PY = JSON.parse(fs.readFileSync(path.join(__dirname, 'py_vectors.json'), 'utf8'));

let fail = 0;
for (const v of VECTORS) {
  const id = DID.fromSeedHex(v.seed);
  const pv = PY[v.seed];
  const okDid = id.did === pv.did;
  const okFp = id.fp === pv.fp;
  const msg = 'hello from flop miner demo block #12 +96 $FLOP';
  const room = 'fp-' + id.fp;
  const nonce = '1750000000000';
  const sig = DID.signText(id, room, msg, nonce);
  const okSig = sig === pv.sig;
  console.log(`seed ${v.seed.slice(0, 8)}…`);
  console.log('  did   ', okDid ? 'OK ' : 'FAIL', id.did);
  console.log('  fp    ', okFp ? 'OK ' : 'FAIL', id.fp);
  console.log('  sig   ', okSig ? 'OK ' : 'FAIL', sig.slice(0, 40), '…');
  if (!(okDid && okFp && okSig)) fail++;
}
console.log(fail === 0 ? '\nALL PASS' : `\n${fail} FAILURES`);
process.exit(fail === 0 ? 0 : 1);
